# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4501b56997de643f95634e488b5f681dbd4dceee1f4dda1190618f32d8cb713a401f73eea45f7ca51a29cd779e602a510abd79c592bb46b210f7949fa6f972a

test:
  secret_key_base: 6a1907e8172a5c967337cde720124d8d7a2c3cb338f5267d52277a71f781a658b4733bfc084183f3e229e8106fc6b0f8ffec826a82d28cd39f0ae693858154c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
